const hsk2Questions = {
    1: [
        { q: "Từ 'Du lịch' trong tiếng Trung là gì?", a: ['上班', '旅游', '运动', '休息'], correct: 1, vocab: "旅游 (lǚyóu) - du lịch - Ví dụ: 我喜欢去旅游。" },
        { q: "Từ 'Thể thao, tập thể dục' trong tiếng Trung là gì?", a: ['跑步', '游泳', '运动', '踢足球'], correct: 2, vocab: "运动 (yùndòng) - thể thao / tập thể dục - Ví dụ: 你最喜欢什么运动？" },
        { q: "Từ 'Chơi bóng đá' trong tiếng Trung là gì?", a: ['打篮球', '打乒乓球', '打羽毛球', '踢足球'], correct: 3, vocab: "踢足球 (tīzúqiú) - chơi bóng đá - Ví dụ: 我最喜欢的运动是踢足球。" },
        { q: "Đại từ 'Nó' tiếng Trung là gì?", a: ['他', '她', '它', '您'], correct: 2, vocab: "它 (tā) - Nó - Ví dụ: 这是我的小狗，它叫小李。" },
        { q: "Từ 'Mắt' trong tiếng Trung là gì?", a: ['鼻子', '眼睛', '嘴巴', '手'], correct: 1, vocab: "眼睛 (yǎnjīng) - Mắt - Ví dụ: 你的眼睛非常漂亮。" },
        { q: "Từ '最' nghĩa là gì?", a: ['Nhất', 'Rất, vô cùng', 'Quá', 'Cũng'], correct: 0, vocab: "最 (zuì) - nhất - Ví dụ: 他的眼睛最漂亮。" },
        { q: "Từ 'Cho rằng, nghĩ rằng' trong tiếng Trung là gì?", a: ['觉得', '决的', '叫的', '学的'], correct: 0, vocab: "觉得 (juéde) - cho rằng, nghĩ rằng - Ví dụ: 我觉得今天他生病了。" },
        { q: "'Tại sao' tiếng Trung là gì?", a: ['怎么', '什么时候', '为什么', '什么'], correct: 2, vocab: "为什么 (wèishénme) - Tại sao - Ví dụ: 你为什么 hôm nay không đi học?" },
        { q: "Tính từ 'Mới' tiếng Trung viết là gì?", a: ['老', '新', '好', '贵'], correct: 1, vocab: "新 (xīn) - mới - Ví dụ: 这是我新的书包。" },
        { q: "Từ 'Cùng nhau' trong tiếng Trung là gì?", a: ['自己', '一起', '都', '只'], correct: 1, vocab: "一起 (yīqǐ) - Cùng nhau - Ví dụ: 今天我跟女朋友出去吃饭。" }
    ],
    2: [
        { q: "Từ 'Thức dậy' tiếng Trung là gì?", a: ['睡觉', '洗澡', '起床', '吃饭'], correct: 2, vocab: "起床 (qǐchuáng) - thức dậy - Ví dụ: 我每天都6点起床。" },
        { q: "Từ 'Bị bệnh, bị ốm' trong tiếng Trung là gì?", a: ['健康', '生病', '上班', '出院'], correct: 1, vocab: "生病 (shēngbìng) - bị bệnh, bị ốm - Ví dụ: 今天我不舒服，可能生病了。" },
        { q: "'Chạy bộ' tiếng Trung là gì?", a: ['散步', '运动', '跑步', '走'], correct: 2, vocab: "跑步 (pǎobù) - chạy bộ - Ví dụ: 我每天早上都出去跑步。" },
        { q: "'Thuốc' tiếng Trung viết chữ Hán thế nào?", a: ['药', '草', '茶', '菜'], correct: 0, vocab: "药 (yào) - thuốc - Ví dụ: 你吃药了吗？" },
        { q: "'休息' nghĩa là gì?", a: ['Làm việc', 'Thể thao / tập thể dục', 'Đi bộ', 'Nghỉ ngơi'], correct: 3, vocab: "休息 (xiūxi) - nghỉ ngơi - Ví dụ: 最近我很忙，没有时间休息。" },
        { q: "Tính từ 'Bận' tiếng Trung là gì?", a: ['累', '忙', '快', '慢'], correct: 1, vocab: "忙 (máng) - bận - Ví dụ: 最近他很忙。" },
        { q: "Từ 'Thời gian' tiếng Trung là gì?", a: ['时候', '小时', '时间', '年'], correct: 2, vocab: "时间 (shíjiān) - thời gian - Ví dụ: 今天我没有时间跟你吃饭。" },
        { q: "'Buổi sáng' tiếng Trung viết là gì?", a: ['上午', '早上', '中午', '晚上'], correct: 1, vocab: "早上 (zǎoshang) - Buổi sáng - Ví dụ: 我每天早上都出去跑步。" },
        { q: "Nghĩa của động từ '知道' là gì?", a: ['Hiểu', 'Nhớ', 'Biết', 'Nhìn'], correct: 2, vocab: "知道 (zhīdào) - Biết - Ví dụ: 我不知道他是谁？" },
        { q: "Từ 'Mỗi' tiếng Trung là gì?", a: ['多', '几', '少', '每'], correct: 3, vocab: "每 (měi) - mỗi - Ví dụ: 我每天都上学。" }
    ],
    3: [
        { q: "'Đồng hồ đeo tay' tiếng Trung là gì?", a: ['手机', '电脑', '手表', '电视'], correct: 2, vocab: "手表 (shǒubiǎo) - đồng hồ đeo tay - Ví dụ: 你的手表多少钱？" },
        { q: "'Tờ báo' tiếng Trung viết chữ Hán thế nào?", a: ['报纸', '书本', '汉语', '纸'], correct: 0, vocab: "报纸 (bàozhǐ) - báo - Ví dụ: 你看过今天的报纸了吗。" },
        { q: "Từ 'Phòng' trong tiếng Trung là gì?", a: ['房子', '班', '房间', '商店'], correct: 2, vocab: "房间 (fángjiān) - Phòng - Ví dụ: 你的房间有大又漂亮。" },
        { q: "Từ 'Chồng' tiếng Trung là gì?", a: ['妻子', '爸爸', '哥哥', '丈夫'], correct: 3, vocab: "丈夫 (zhàngfu) - chồng - Ví dụ: 我丈夫在上海工作。" },
        { q: "Từ 'Màu sắc' trong tiếng Trung là gì?", a: ['东西', '衣服', '颜色', '身体'], correct: 2, vocab: "颜色 (yánsè) - màu sắc - Ví dụ: 你最喜欢什么颜色？" },
        { q: "'Màu đỏ' tiếng Trung là gì?", a: ['黑色', '红色', '白色', '粉色'], correct: 1, vocab: "红色 (hóngsè) - màu đỏ - Ví dụ: 红色的是我的。" },
        { q: "Từ 'Bên trái' tiếng Trung viết là gì?", a: ['右边', '下边', '左边', '上边'], correct: 2, vocab: "左边 (zuǒbian) - bên trái - Ví dụ: 银行在学校的左边。" },
        { q: "Từ 'Bên cạnh' trong tiếng Trung là gì?", a: ['后面', '前面', '里面', '旁边'], correct: 3, vocab: "旁边 (pángbiān) - bên cạnh - Ví dụ: 学校在银行的旁边。" },
        { q: "'Sữa bò' tiếng Trung là gì?", a: ['水', '茶', '牛奶', '咖啡'], correct: 2, vocab: "牛奶 (niúnǎi) - sữa bò - Ví dụ: 我不喜欢喝牛奶？" },
        { q: "'Nghìn' tiếng Trung là gì?", a: ['十', '百', '千', '万'], correct: 2, vocab: "千 (qiān) - nghìn - Ví dụ: 我的手表一千人民币。" }
    ],
    4: [
        { q: "Từ 'Sinh nhật' tiếng Trung là gì?", a: ['节日', '生日', '明天', '昨天'], correct: 1, vocab: "生日 (shēngrì) - Sinh nhật - Ví dụ: 你的生日是几月几号？" },
        { q: "Từ 'Vui vẻ' trong tiếng Trung là gì?", a: ['快乐', '难过', '生气', '漂亮'], correct: 0, vocab: "快乐 (kuàilè) - vui vẻ - Ví dụ: 祝你生日快乐。" },
        { q: "Từ 'Buổi tối' tiếng Trung viết chữ Hán thế nào?", a: ['早上', '下午', '晚上', '中午'], correct: 2, vocab: "晚上 (wǎnshàng) - buổi tối - Ví dụ: 晚上我经常跟父母去喝咖啡。" },
        { q: "Động từ 'Bắt đầu' tiếng Trung là gì?", a: ['结束', '准备', '开始', '休息'], correct: 2, vocab: "开始 (kāishǐ) - bắt đầu - Ví dụ: 我 từ 7 tuổi bắt đầu học tiếng Trung." },
        { q: "Từ 'Đã' trong tiếng Trung là gì?", a: ['正在', '已经', '会', '新'], correct: 1, vocab: "已经 (yǐjīng) - đã - Ví dụ: 他已经回家了。" },
        { q: "Động từ 'Giới thiệu' tiếng Trung là gì?", a: ['介绍', '帮助', '认识', '知道'], correct: 0, vocab: "介绍 (jièshào) - giới thiệu - Ví dụ: 老师给我们介绍一个新的朋友。" },
        { q: "'Giúp đỡ' tiếng Trung viết là gì?", a: ['让', '给', '帮', '找'], correct: 2, vocab: "帮 (bāng) - giúp, giúp đỡ - Ví dụ: 你可以帮我一下吗？" },
        { q: "Từ 'Rất, vô cùng' trong tiếng Trung là gì?", a: ['非常', '飞唱', '飞常', '费常'], correct: 0, vocab: "非常 (fēicháng) - rất, vô cùng - Ví dụ: 他的房间非常大。" },
        { q: "Tính từ 'Dài' tiếng Trung là gì?", a: ['短', '高', '远', '长'], correct: 3, vocab: "长 (cháng) - dài, lâu - Ví dụ: 这条路很长。" },
        { q: "Động từ 'Hỏi' viết chữ Hán thế nào?", a: ['说', '问', '听', '读'], correct: 1, vocab: "问 (wèn) - hỏi - Ví dụ: 别问我。我不知道。" }
    ],
    5: [
        { q: "Từ 'Bên ngoài' tiếng Trung là gì?", a: ['里面', '前面', '外面', '后面'], correct: 2, vocab: "外面 (wàimiàn) - bên ngoài - Ví dụ: 我在外面等你。" },
        { q: "Từ 'Chuẩn bị, định, dự định' trong tiếng Trung là gì?", a: ['开始', '准备', '结束', '复习'], correct: 1, vocab: "准备 (zhǔnbèi) - chuẩn bị, định, dự định - Ví dụ: 他准备去中国学习中文。" },
        { q: "'Con cá' tiếng Trung viết chữ Hán thế nào?", a: ['羊', '牛', '鱼', '鸟'], correct: 2, vocab: "鱼 (yú) - cá - Ví dụ: 河里有很多鱼。" },
        { q: "'Bài kiểm tra, cuộc thi' tiếng Trung là gì?", a: ['学习', '考试', '问题', '课'], correct: 1, vocab: "考试 (kǎoshì) - cuộc thi, bài kiểm tra - Ví dụ: 明天有一个中文的考试。" },
        { q: "Từ 'Nghĩa, ý nghĩa' trong tiếng Trung là gì?", a: ['声音', '问题', '意思', '事情'], correct: 2, vocab: "意思 (yìsi) - nghĩa, ý nghĩa - Ví dụ: 我 không hiểu ý thầy nói gì." },
        { q: "'Cà phê' tiếng Trung viết là gì?", a: ['咖啡', '牛奶', '果汁', '啤酒'], correct: 0, vocab: "咖啡 (kāfēi) - cà phê - Ví dụ: 就喝咖啡吧。" },
        { q: "Từ 'Sau này' trong tiếng Trung là gì?", a: ['以前', '现在', '以后', '今天'], correct: 2, vocab: "以后 (yǐhòu) - sau này - Ví dụ: 考试以后他打算去中国旅游。" },
        { q: "Từ 'Tuyệt, khá tốt' trong tiếng Trung là gì?", a: ['错了', '不错', '很差', '一般'], correct: 1, vocab: "不错 (bùcuò) - tuyệt, khá tốt - Ví dụ: 很不错，挺不错……" },
        { q: "Lượng từ dành cho quần áo là gì?", a: ['个', '本', '块', '件'], correct: 3, vocab: "件 (jiàn) - cái, chiếc - Ví dụ: 这件衣服太贵。" },
        { q: "Có thể, tạm được tiếng Trung là gì?", a: ['觉得', '要', '可以', '想'], correct: 2, vocab: "可以 (kěyǐ) - không tệ, tạm được - Ví dụ: 他的成绩还可以。" }
    ],
    6: [
        { q: "Từ 'Xe đạp' tiếng Trung là gì?", a: ['汽车', '自行车', '火车', '飞机'], correct: 1, vocab: "自行车 (zìxíngchē) - xe đạp - Ví dụ: 我骑自行车去学校。" },
        { q: "Từ 'Mì' trong tiếng Trung là gì?", a: ['米饭', '包子', '面条', '面包'], correct: 2, vocab: "面条 (miàntiáo) - Mì - Ví dụ: 我不喜欢吃面条。" },
        { q: "'Thịt cừu' tiếng Trung viết là gì?", a: ['羊肉', '猪肉', '牛肉', '鸡肉'], correct: 0, vocab: "羊肉 (yángròu) - thịt cừu - Ví dụ: 中国人喜欢吃羊肉。" },
        { q: "Cụm từ 'Chơi bóng rổ' tiếng Trung là gì?", a: ['踢足球', '游泳', '跑步', '打篮球'], correct: 3, vocab: "打篮球 (dǎlánqiú) - Chơi bóng rổ - Ví dụ: 我喜欢打篮球。" },
        { q: "Liên từ 'Bởi vì' tiếng Trung là gì?", a: ['所以', '因为', '但是', '虽然'], correct: 1, vocab: "因为 (yīnwèi) - bởi vì - Ví dụ: 因为……所以……" },
        { q: "Liên từ 'Cho nên' tiếng Trung là gì?", a: ['所以', '因为', '但是', '还是'], correct: 0, vocab: "所以 (suǒyǐ) - cho nên - Ví dụ: 因为他每天都跑步，所以身体很好。" },
        { q: "Động từ 'Bơi lội' tiếng Trung là gì?", a: ['旅游', '运动', '游泳', '跳舞'], correct: 2, vocab: "游泳 (yóuyǒng) - bơi - Ví dụ: 我不会游泳。" },
        { q: "Phó từ 'Thường xuyên' tiếng Trung viết là gì?", a: ['已经', '非常', '一直', '经常'], correct: 3, vocab: "经常 (jīngcháng) - thường xuyên - Ví dụ: 我经常坐公共汽车去学校。" },
        { q: "Từ 'Kilogram' trong tiếng Trung là gì?", a: ['公斤', '米', '升', '克'], correct: 0, vocab: "公斤 (gōngjīn) - Kilogram - Ví dụ: 苹果一公斤多少钱？" },
        { q: "Từ 'Chị gái' tiếng Trung là gì?", a: ['妹妹', '姐姐', '哥哥', '妈妈'], correct: 1, vocab: "姐姐 (jiĕjie) - chị gái - Ví dụ: 你姐姐很漂亮。" }
    ],
    7: [
        { q: "Từ 'Lớp học' tiếng Trung là gì?", a: ['教室', '学校', '房间', '饭店'], correct: 0, vocab: "教室 (jiàoshì) - lớp học - Ví dụ: 教室里有多少学生？" },
        { q: "Từ 'Sân bay' trong tiếng Trung là gì?", a: ['火车站', '车站', '机场', '公司'], correct: 2, vocab: "机场 (jīchǎng) - Sân bay - Ví dụ: 从宿舍到机场远不远？" },
        { q: "Động từ 'Cách' tiếng Trung là gì?", a: ['去', '离', '从', '到'], correct: 1, vocab: "离 (lí) - cách - Ví dụ: 你家离公司远吗？" },
        { q: "Từ 'Công ty' tiếng Trung viết là gì?", a: ['医院', '商店', '公司', '学校'], correct: 2, vocab: "公司 (gōngsī) - công ty - Ví dụ: 你的公司在哪儿？" },
        { q: "Tính từ 'Xa' tiếng Trung là gì?", a: ['近', '高', '远', '长'], correct: 2, vocab: "远 (yuǎn) - Xa - Ví dụ: 从我家到公司很远。" },
        { q: "'Xe buýt' tiếng Trung là gì?", a: ['出租车', '自行车', '公共汽车', '火车'], correct: 2, vocab: "公共汽车 (gōnggòngqìchē) - xe buýt - Ví dụ: 我坐公共汽车去学校。" },
        { q: "Từ 'Giờ ' tiếng Trung là gì?", a: ['时间', '小时', '分钟', '時候'], correct: 1, vocab: "小时 (xiǎoshí) - giờ (đồng hồ) - Ví dụ: 坐火车去北京要一个多小时。" },
        { q: "Tính từ 'Chậm' tiếng Trung viết là gì?", a: ['快', '慢', '少', '错'], correct: 1, vocab: "慢 (màn) - chậm - Ví dụ: 他汉语说得很慢。" },
        { q: "Tính từ 'Nhanh' tiếng Trung là gì?", a: ['慢', '快', '多', '对'], correct: 1, vocab: "快 (kuài) - nhanh - Ví dụ: 他跑得很快。" },
        { q: "Động từ 'Đi bộ' tiếng Trung là gì?", a: ['跑', '来', '去', '走'], correct: 3, vocab: "走 (zǒu) - đi bộ - Ví dụ: 我每天 đều đi bộ đi học." }
    ],
    8: [
        { q: "Phó từ 'Lại, hãy ' tiếng Trung là gì?", a: ['还', '也', '再', '就'], correct: 2, vocab: "再 (zài) - lại, lại lần nữa - Ví dụ: 你帮我再说一遍吧。" },
        { q: "Động từ 'Để, bảo, nhường' tiếng Trung là gì?", a: ['让', '给', '帮', '找'], correct: 0, vocab: "让 (ràng) - để, bảo - Ví dụ: 妈妈让你去吃饭。" },
        { q: "Từ 'Nói cho biết' trong tiếng Trung là gì?", a: ['听', '想', '告诉', '回答'], correct: 2, vocab: "告诉 (gàosu) - nói cho biết" },
        { q: "Động từ 'Đợi' tiếng Trung viết là gì?", a: ['找', '等', '看', '听'], correct: 1, vocab: "等 (děng) - đợi - Ví dụ: 我在外面等你。" },
        { q: "Động từ 'Tìm, kiếm' tiếng Trung là gì?", a: ['买', '卖', '找', '送'], correct: 2, vocab: "找 (zhǎo) - tìm - Ví dụ: 你找谁？" },
        { q: "Từ 'Sự việc' trong tiếng Trung là gì?", a: ['东西', '时间', '事情', '人'], correct: 2, vocab: "事情 (shìqing) - sự việc - Ví dụ: 你找我有什么事情？" },
        { q: "Từ 'Nhân viên phục vụ' tiếng Trung là gì?", a: ['服务员', '老师', '医生', '学生'], correct: 0, vocab: "服务员 (fúwùyuán) - nhân viên phục vụ - Ví dụ: 服务员 giúp tôi gọi taxi." },
        { q: "Tính từ 'Trắng' tiếng Trung là gì?", a: ['黑', '红', '白', '粉'], correct: 2, vocab: "白 (bái) - có màu trắng - Ví dụ: 这件白色的衣服还可以。" },
        { q: "Tính từ 'Đen' tiếng Trung viết là gì?", a: ['白', '黑', '蓝', '绿'], correct: 1, vocab: "黑 (hēi) - có màu đen - Ví dụ: 这条黑色的裤子很不错。" },
        { q: "Tính từ 'Đắt' tiếng Trung là gì?", a: ['便宜', '高', '贵', '多'], correct: 2, vocab: "贵 (guì) - đắt - Ví dụ: 这件衣服太贵了。" }
    ],
    9: [
        { q: "Tính từ 'Sai' tiếng Trung là gì?", a: ['对', '错', '慢', '快'], correct: 1, vocab: "错 (cuò) - sai - Ví dụ: 你说错了。" },
        { q: "Giới từ 'Từ ' tiếng Trung là gì?", a: ['到', '在', '离', '从'], correct: 3, vocab: "从 (cóng) - từ - Ví dụ: 你从几岁开始学习汉语？" },
        { q: "Từ 'Nhảy, khiêu vũ' trong tiếng Trung là gì?", a: ['唱歌', '游泳', '跳舞', '跑步'], correct: 2, vocab: "跳舞 (tiàowǔ) - nhảy, khiêu vũ - Ví dụ: 他喜欢跟女朋友跳舞。" },
        { q: "Từ 'Thứ nhất, đầu tiên' tiếng Trung là gì?", a: ['一次', '第一', '一件', '一起'], correct: 1, vocab: "第一 (dìyī) - thứ nhất, đầu tiên - Ví dụ: 这是我第一次来中国。" },
        { q: "Từ 'Mong, hy vọng' trong tiếng Trung là gì?", a: ['希望', '准备', '决定', '开始'], correct: 0, vocab: "希望 (xīwàng) - mong, hy vọng - Ví dụ: 我希望今年能跟父母过春节。" },
        { q: "Từ 'Vấn đề, câu hỏi' tiếng Trung viết là gì?", a: ['意思', '事情', '问题', '题'], correct: 2, vocab: "问题 (wèntí) - vấn đề, câu hỏi" },
        { q: "Từ 'Hoan nghênh' trong tiếng Trung là gì?", a: ['再见', '谢谢', '对不起', '欢迎'], correct: 3, vocab: "欢迎 (huānyíng) - hoan nghênh - Ví dụ: 欢迎光临。" },
        { q: "Động từ 'Đi làm' tiếng Trung là gì?", a: ['下班', '工作', '上课', '上班'], correct: 3, vocab: "上班 (shàngbān) - đi làm - Ví dụ: 你每天几点上班？" },
        { q: "Động từ 'Hiểu' tiếng Trung là gì?", a: ['知道', '懂', '认识', '觉得'], correct: 1, vocab: "懂 (dǒng) - hiểu, biết - Ví dụ: 我听不懂老师的问题。" },
        { q: "Từ 'Xong, hết' trong tiếng Trung là gì?", a: ['完', '开始', '在做', '没完'], correct: 0, vocab: "完 (wán) - xong, hết - Ví dụ: 你做完了吗？" }
    ],
    10: [
        { q: "Từ 'Giờ học, môn, bài' trong tiếng Trung là gì?", a: ['作业', '课', '学校', '老师'], correct: 1, vocab: "课 (kè) - giờ học, môn, bài - Ví dụ: 明天上午还有汉语课呢。" },
        { q: "Động từ 'Giúp đỡ' tiếng Trung viết là gì?", a: ['介绍', '告诉', '帮助', '准备'], correct: 2, vocab: "帮助 (bāngzhù) - giúp ích, giúp đỡ - Ví dụ: 他经常帮助老人过马路。" },
        { q: "Phó từ 'Đừng' tiếng Trung là gì?", a: ['不', '没', '别', '非常'], correct: 2, vocab: "别 (bié) - Đừng - Ví dụ: 睡觉前你别喝咖啡。" },
        { q: "Từ 'Anh trai' tiếng Trung là gì?", a: ['弟弟', '哥哥', '姐姐', '爸爸'], correct: 1, vocab: "哥哥 (gēge) - anh trai - Ví dụ: 我没有哥哥。" },
        { q: "'Trứng gà' tiếng Trung viết là gì?", a: ['牛肉', '羊肉', '鸡蛋', '米饭'], correct: 2, vocab: "鸡蛋 (jīdàn) - trứng - Ví dụ: 你帮我去超市买鸡蛋吧。" },
        { q: "'Dưa hấu' tiếng Trung là gì?", a: ['苹果', '西瓜', '水果', '茶'], correct: 1, vocab: "西瓜 (xīguā) - dưa hấu - Ví dụ: 他不喜欢吃西瓜。" },
        { q: "Phó từ 'Đang ' tiếng Trung là gì?", a: ['已经', '准备', '开始', '正在'], correct: 3, vocab: "正在 (zhèngzài) - đang - Ví dụ: 妈妈正在准备午饭呢。" },
        { q: "'Điện thoại di động' tiếng Trung là gì?", a: ['电脑', '电视', '电话', '手机'], correct: 3, vocab: "手机 (shǒujī) - điện thoại di động - Ví dụ: 你看见我的手机了吗？" },
        { q: "Động từ 'Giặt, rửa' tiếng Trung viết là gì?", a: ['洗', '做', '买', '穿'], correct: 0, vocab: "洗 (xǐ) - giặt, rửa - Ví dụ: 那件衣服我帮你洗了。" },
        { q: "Câu 'Đừng tìm nữa' tiếng Trung nói thế nào?", a: ['别买了', '别看了', '别找了', '别问了'], correct: 2, vocab: "别找了 (bié zhǎo le) - Đừng tìm nữa" }
    ],
    11: [
        { q: "Từ 'Hát' trong tiếng Trung là gì?", a: ['听', '跳舞', '唱歌', '读'], correct: 2, vocab: "唱歌 (chànggē) - Hát - Ví dụ: 我不喜欢唱歌。" },
        { q: "Tính từ 'Nam ' tiếng Trung là gì?", a: ['女', '男', '老', '少'], correct: 1, vocab: "男 (nán) - thuộc về nam giới - Ví dụ: 他是我男朋友。" },
        { q: "Tính từ 'Nữ ' tiếng Trung viết là gì?", a: ['男', '女', '阴', '阳'], correct: 1, vocab: "女 (nǚ) - thuộc về nữ giới - Ví dụ: 她不是我女朋友。" },
        { q: "Từ 'Trẻ em, trẻ con' trong tiếng Trung là gì?", a: ['大人', '父母', '孩子', '学生'], correct: 2, vocab: "孩子 (háizi) - trẻ em, trẻ con - Ví dụ: 那个孩子又聪明又漂亮。" },
        { q: "Từ 'Bên phải' tiếng Trung là gì?", a: ['左边', '右边', '前面', '后面'], correct: 1, vocab: "右边 (yòubian) - bên phải - Ví dụ: 我学校在银行的右边。" },
        { q: "Giới từ dùng trong so sánh 'Hơn, so với' là gì?", a: ['从', '离', '给', '比'], correct: 3, vocab: "比 (bǐ) - hơn (dùng trong cấu trúc so sánh) - Ví dụ: 他比我高得多。" },
        { q: "Tính từ 'Rẻ' tiếng Trung là gì?", a: ['贵', '少', '便宜', '错'], correct: 2, vocab: "便宜 (piányi) - rẻ - Ví dụ: 这件衣服很便宜。" },
        { q: "Từ 'Nói chuyện' trong tiếng Trung là gì?", a: ['听', '说话', '故事', '读'], correct: 1, vocab: "说话 (shuō huà) - nói chuyện - Ví dụ: 前边说话的那个人是我的老师。" },
        { q: "'Có thể, có lẽ' tiếng Trung viết là gì?", a: ['可以', '觉得', '可能', '知道'], correct: 2, vocab: "可能 (kěnéng) - có thể, có lẽ - Ví dụ: 你可能不认识他。" },
        { q: "Từ 'Năm ngoái' tiếng Trung là gì?", a: ['明天', '今年', '明年', '去年'], correct: 3, vocab: "去年 (qùnián) - năm ngoái - Ví dụ: 去年我跟父母去中国旅游。" }
    ],
    12: [
        { q: "Trợ từ chỉ kết quả, mức độ đứng sau động từ là gì?", a: ['的', '得', '地', '了'], correct: 1, vocab: "得 (de) - trợ từ chỉ mức độ/kết quả" },
        { q: "Từ 'Vợ' tiếng Trung là gì?", a: ['丈夫', '妈妈', '妻子', '姐姐'], correct: 2, vocab: "妻子 (qīzi) - Vợ - Ví dụ: 我妻子比我做得好。" },
        { q: "Từ 'Tuyết' tiếng Trung viết là gì?", a: ['雨', '阴', '雪', '晴'], correct: 2, vocab: "雪 (xuě) - Tuyết - Ví dụ: 外面下雪了。" },
        { q: "'Số không ' tiếng Trung là gì?", a: ['一', '十', '百', '零'], correct: 3, vocab: "零 (líng) - số không - Ví dụ: 今天零下10度。" },
        { q: "Từ 'Độ' trong tiếng Trung là gì?", a: ['度', '米', '公斤', '小时'], correct: 0, vocab: "度 (dù) - độ - Ví dụ: 今天天气高达35度。" },
        { q: "Động từ 'Mặc, mang ' tiếng Trung là gì?", a: ['洗', '穿', '脱', '买'], correct: 1, vocab: "穿 (chuān) - mặc, mang - Ví dụ: 你穿得太少了。" },
        { q: "Động từ 'Vào' tiếng Trung viết là gì?", a: ['出', '回', '走', '进'], correct: 3, vocab: "进 (jìn) - vào - Ví dụ: 请您进教室。" },
        { q: "Từ 'Em trai' tiếng Trung là gì?", a: ['哥哥', '弟弟', '妹妹', '姐姐'], correct: 1, vocab: "弟弟 (dìdi) - em trai - Ví dụ: 我弟弟非常喜欢打篮球。" },
        { q: "Tính từ 'Gần' tiếng Trung là gì?", a: ['远', '近', '长', '短'], correct: 1, vocab: "近 (jìn) - gần - Ví dụ: 我家离学校很近。" },
        { q: "Câu 'Bạn mặc ít quá' tiếng Trung nói thế nào?", a: ['你买得太少了', '你穿得太少了', '你穿得太小了', '你吃得太少了'], correct: 1, vocab: "你穿得太少了 (nǐ chuān de tài shǎo le)" }
    ],
    13: [
        { q: "Trợ từ chỉ trạng thái đang diễn ra là gì?", a: ['了', '过', '着', '呢'], correct: 2, vocab: "着 (zhe) - trợ từ chỉ trạng thái - Ví dụ: 门开着呢。" },
        { q: "Từ 'Tay' trong tiếng Trung là gì?", a: ['脚', '眼睛', '手', '嘴巴'], correct: 2, vocab: "手 (shǒu) - tay - Ví dụ: 他受伤了，手很疼。" },
        { q: "Động từ 'Cầm, lấy' tiếng Trung là gì?", a: ['送', '给', '买', '拿'], correct: 3, vocab: "拿 (ná) - cầm - Ví dụ: 你帮我拿书包过来吧。" },
        { q: "Từ 'Bút chì' tiếng Trung viết là gì?", a: ['报纸', '铅笔', '书包', '手表'], correct: 1, vocab: "铅笔 (qiānbǐ) - bút chì - Ví dụ: 你能借我一只铅笔吗？" },
        { q: "Từ 'Lớp học' trong tiếng Trung là gì?", a: ['学校', '公司', '班', '医院'], correct: 2, vocab: "班 (bān) - lớp học - Ví dụ: 你是几班的学生？" },
        { q: "Động từ 'Lớn lên, phát triển' tiếng Trung là gì?", a: ['长', '生', '做', '玩'], correct: 0, vocab: "长 (zhǎng) - sinh ra, mọc - Ví dụ: 他在上海长大的。" },
        { q: "Động từ 'Cười' tiếng Trung viết là gì?", a: ['哭', '叫', '问', '笑'], correct: 3, vocab: "笑 (xiào) - cười - Ví dụ: 他总是笑着跟别人说话。" },
        { q: "Từ 'Khách sạn' tiếng Trung là gì?", a: ['饭店', '商店', '宾馆', '医院'], correct: 2, vocab: "宾馆 (bīnguǎn) - Khách sạn - Ví dụ: 宾馆在银行的旁边。" },
        { q: "Phó từ 'Thẳng, liên tục' tiếng Trung là gì?", a: ['已经', '非常', '一起', '一直'], correct: 3, vocab: "一直 (yǐzhí) - thẳng - Ví dụ: 从这儿一直往前走。" },
        { q: "Giới từ 'Về phía, hướng về' tiếng Trung là gì?", a: ['从', '离', '往', '到'], correct: 2, vocab: "往 (wǎng) - về phía - Ví dụ: 你从这儿往前走。" }
    ],
    14: [
        { q: "Tính từ 'Thú vị, hấp dẫn' tiếng Trung là gì?", a: ['快乐', '有意思', '不错', '漂亮'], correct: 1, vocab: "有意思 (yǒu yìsi) - hấp dẫn - Ví dụ: 这部电影的内容很有意思。" },
        { q: "Liên từ 'Nhưng' tiếng Trung viết là gì?", a: ['所以', '因为', '虽然', '但是'], correct: 3, vocab: "但是 (dànshì) - nhưng - Ví dụ: 他是一个优秀的学生，但是……" },
        { q: "Từ 'Mặc dù, tuy' trong tiếng Trung là gì?", a: ['虽然', '因为', '所以', '但是'], correct: 0, vocab: "虽然 (suīrán) - mặc dù, tuy - Ví dụ: 虽然他很忙，但是还……" },
        { q: "Lượng từ 'Lần' tiếng Trung là gì?", a: ['件', '块', '次', '本'], correct: 2, vocab: "次 (cì) - lần - Ví dụ: 我去过河内好几次。" },
        { q: "Từ 'Chơi, chơi đùa' trong tiếng Trung là gì?", a: ['学习', '休息', '玩儿', '工作'], correct: 2, vocab: "玩儿 (wánr) - chơi, chơi đùa - Ví dụ: 我们出去玩儿玩儿吧。" },
        { q: "Tính từ 'Nắng, trời quang' tiếng Trung là gì?", a: ['阴', '雨', '雪', '晴'], correct: 3, vocab: "晴 (qíng) - có nắng, nắng ráo - Ví dụ: 晴天让人的心情特别好。" },
        { q: "'Một trăm' tiếng Trung viết là gì?", a: ['千', '百', '万', '十'], correct: 1, vocab: "百 (bǎi) - một trăm, trăm - Ví dụ: 两百块还可以。" },
        { q: "Cấu trúc 'Tuy... nhưng...' tiếng Trung là gì?", a: ['因为... 所以...', '虽然... 但是...', '从... 到...', '离... 远...'], correct: 1, vocab: "虽然...但是... (suīrán...dànshì...)" },
        { q: "Từ 'Phim, điện ảnh' tiếng Trung là gì?", a: ['电视', '电脑', '电影', '手机'], correct: 2, vocab: "电影 (diànyǐng) - Phim" },
        { q: "Câu 'Bộ phim này rất thú vị' tiếng Trung nói thế nào?", a: ['这个电影很好看', '这个电影很有意思', '这个电视很有意思', '这个电影很不错'], correct: 1, vocab: "这部电影很有意思 (zhè bù diànyǐng hěn yǒu yìsi)" }
    ],
    15: [
        { q: "Từ 'Ngày' tiếng Trung là gì?", a: ['号', '角', '日', '月'], correct: 2, vocab: "日 (rì) - ngày - Ví dụ: 你的生日是几月几日？" },
        { q: "Từ 'Năm mới, Tết' trong tiếng Trung là gì?", a: ['去年', '今年', '明年', '新年'], correct: 3, vocab: "新年 (xīnnián) - năm mới, Tết - Ví dụ: 祝大家新年快乐。" },
        { q: "Từ 'Vé' tiếng Trung viết là gì?", a: ['钱', '票', '纸', '报纸'], correct: 1, vocab: "票 (piào) - vé - Ví dụ: 你买火车票了吗？" },
        { q: "'Ga tàu hỏa' tiếng Trung là gì?", a: ['机场', '车站', '火车站', '地铁站'], correct: 2, vocab: "火车站 (huǒchēzhàn) - ga tàu hoả - Ví dụ: 我在火车站等你。" },
        { q: "Từ 'Mọi người' trong tiếng Trung là gì?", a: ['大家庭', '大家', '朋友', '班'], correct: 1, vocab: "大家 (dàjiā) - Mọi người - Ví dụ: 祝大家新年快乐。" },
        { q: "Phó từ 'Càng, hơn nữa' tiếng Trung là gì?", a: ['最', '很', '更', '太'], correct: 2, vocab: "更 (gèng) - càng, hơn nữa - Ví dụ: 希望我们的公司明年更好。" },
        { q: "Từ 'Em gái' tiếng Trung viết là gì?", a: ['姐姐', '妹妹', '哥哥', '弟弟'], correct: 1, vocab: "妹妹 (mèimei) - em gái - Ví dụ: 你妹妹多大了？" },
        { q: "Tính từ 'Râm, u ám, nhiều mây' tiếng Trung là gì?", a: ['晴', '阴', '雨', '雪'], correct: 1, vocab: "阴 (yīn) - u ám, nhiều mây - Ví dụ: 天阴了，我要回去了。" },
        { q: "Câu 'Năm mới sắp đến rồi' tiếng Trung nói thế nào?", a: ['新年要来了', '新年就要到了', '已经新年了', '新年到了'], correct: 1, vocab: "新年就要到了 (xīnnián jiù yào dào le)" },
        { q: "Chúc 'Mọi người năm mới vui vẻ' tiếng Trung nói thế nào?", a: ['祝大家生日快乐', '祝大家新年好', '祝大家新年快乐', '祝你新年快乐'], correct: 2, vocab: "祝大家新年快乐 (zhù dàjiā xīnnián kuàilè)" }
    ]
};
